name: MPstain
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - appdirs=1.4.4=py_0
  - arrow-cpp=0.15.1=py37h7cd5009_5
  - aws-requests-auth=0.4.3=py_0
  - blas=1.0=mkl
  - boost-cpp=1.71.0=h7b6447c_0
  - boto3=1.9.66=py37_0
  - botocore=1.12.67=py37_0
  - brotli=1.0.9=he6710b0_2
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.16.1=h7b6447c_0
  - ca-certificates=2020.10.14=0
  - certifi=2020.6.20=pyhd3eb1b0_3
  - cffi=1.14.3=py37he30daa8_0
  - chardet=3.0.4=py37_1003
  - click=7.1.2=py_0
  - cryptography=3.1.1=py37h1ba5d50_0
  - cudatoolkit=10.2.89=hfd86e86_1
  - dnspython=1.16.0=py37_0
  - docutils=0.16=py37_1
  - double-conversion=3.1.5=he6710b0_1
  - flask=1.1.2=py_0
  - flask-cors=3.0.9=py_0
  - flask-json=0.3.4=py_0
  - freetype=2.10.4=h5ab3b9f_0
  - gflags=2.2.2=he6710b0_0
  - glog=0.4.0=he6710b0_0
  - grpc-cpp=1.26.0=hf8bcb03_0
  - icu=58.2=he6710b0_3
  - idna=2.10=py_0
  - intel-openmp=2020.2=254
  - itsdangerous=1.1.0=py37_0
  - jinja2=2.11.2=py_0
  - jmespath=0.10.0=py_0
  - jpeg=9b=h024ee3a_2
  - jsonlines=1.2.0=py_2
  - lcms2=2.11=h396b838_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libboost=1.71.0=h97c9712_0
  - libedit=3.1.20191231=h14c3975_1
  - libevent=2.1.8=h1ba5d50_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libpng=1.6.37=hbc83047_0
  - libprotobuf=3.11.2=hd408876_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_0
  - lz4-c=1.8.1.2=h14c3975_0
  - markupsafe=1.1.1=py37h14c3975_1
  - mkl=2020.2=256
  - mkl-service=2.3.0=py37he904b0f_0
  - mkl_fft=1.2.0=py37h23d657b_0
  - mkl_random=1.1.1=py37h0573a6f_0
  - ncurses=6.2=he6710b0_1
  - ninja=1.10.1=py37hfd86e86_0
  - numpy=1.19.2=py37h54aff64_0
  - numpy-base=1.19.2=py37hfa32c7d_0
  - olefile=0.46=py37_0
  - openssl=1.1.1h=h7b6447c_0
  - packaging=20.4=py_0
  - pandas=1.1.3=py37he6710b0_0
  - pillow=8.0.1=py37he98fc37_0
  - pip=20.2.4=py37h06a4308_0
  - pyarrow=0.15.1=py37h0573a6f_0
  - pycparser=2.20=py_2
  - pyopenssl=19.1.0=py_1
  - pyparsing=2.4.7=py_0
  - pysocks=1.7.1=py37_1
  - python=3.7.9=h7579374_0
  - python-dateutil=2.8.0=py37_0
  - pytorch=1.6.0=py3.7_cuda10.2.89_cudnn7.6.5_0
  - pytz=2020.1=py_0
  - quilt3=3.1.10=py37_0
  - re2=2019.08.01=he6710b0_0
  - readline=8.0=h7b6447c_0
  - requests=2.24.0=py_0
  - requests-futures=1.0.0=py_2
  - ruamel.yaml=0.16.12=py37h7b6447c_1
  - ruamel.yaml.clib=0.2.2=py37h7b6447c_0
  - s3transfer=0.1.13=py37_0
  - setuptools=50.3.1=py37h06a4308_1
  - six=1.15.0=py_0
  - snappy=1.1.8=he6710b0_0
  - sqlite=3.33.0=h62c20be_0
  - thrift-cpp=0.11.0=h02b749d_3
  - tk=8.6.10=hbc83047_0
  - torchvision=0.7.0=py37_cu102
  - tqdm=4.50.2=py_0
  - uriparser=0.9.3=he6710b0_1
  - urllib3=1.24.3=py37_0
  - werkzeug=1.0.1=py_0
  - wheel=0.35.1=py_0
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.3.7=h0b5b093_0
  - pip:
    - aicsimageio==3.0.7
    - cycler==0.10.0
    - decorator==4.4.2
    - fnet==0.2.0
    - future==0.18.2
    - imageio==2.9.0
    - jsonpatch==1.26
    - jsonpointer==2.0
    - kiwisolver==1.3.1
    - matplotlib==3.3.2
    - networkx==2.5
    - opencv-python==4.4.0.46
    - pytorch-toolbelt==0.4.0
    - pywavelets==1.1.1
    - pyzmq==19.0.2
    - scikit-image==0.17.2
    - scipy==1.5.4
    - tifffile==0.15.1
    - torchfile==0.1.0
    - torchnet==0.0.4
    - tornado==6.1
    - visdom==0.1.8.9
    - websocket-client==0.57.0
prefix: /home/yihsiao/.conda/envs/MPstain

